name: Furia App pipeline
on:
  push:
    branches:
      - main

jobs:
    # build-application:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - uses: actions/checkout@v4

    #     - uses: actions/setup-node@v4
    #       with:
    #         node-version: 20
    #       run: |
    #         npm install
    #         npm run build

    test-application:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-node@v4
          with:
            node-version: 20
        - run: |
            cd server
            npm install
            npm run test

    lint-application:
      runs-on: ubuntu-latest
      needs: [test-application]
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Running lint
          run: |
            cd server
            npm install
            npm run lint
#  build-and-push-docker-image:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#       uses: actions/checkout@v4

#     - name: Login to Docker Hub
#       uses: docker/login-action@v3
#       with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Build and push Docker image
#        uses: docker/build-push-action@v5
#        with:
#          context: server/src
#          file: server/Dockerfile
#          push: true
#          tags: herosnuciatelli/furia-app:v${{ github.run_number }}
